package com.km.knowledgemessage.Model;

public class CardNum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_num.card_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    private Long cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_num.like_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    private Long likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_num.comment_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    private Long commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_num.collect_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    private Long collectNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_num.card_id
     *
     * @return the value of card_num.card_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_num.card_id
     *
     * @param cardId the value for card_num.card_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_num.like_num
     *
     * @return the value of card_num.like_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public Long getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_num.like_num
     *
     * @param likeNum the value for card_num.like_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public void setLikeNum(Long likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_num.comment_num
     *
     * @return the value of card_num.comment_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public Long getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_num.comment_num
     *
     * @param commentNum the value for card_num.comment_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public void setCommentNum(Long commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_num.collect_num
     *
     * @return the value of card_num.collect_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public Long getCollectNum() {
        return collectNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_num.collect_num
     *
     * @param collectNum the value for card_num.collect_num
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public void setCollectNum(Long collectNum) {
        this.collectNum = collectNum;
    }
}