package com.km.knowledgemessage.Model;

public class Card {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.creator_id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.gmt_create
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.gmt_modified
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.is_public
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private Boolean isPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.title
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_description
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private String cardDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.img_src
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private String imgSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.label_name
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.user_id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.card_text
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    private String cardText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.id
     *
     * @return the value of card.id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.id
     *
     * @param id the value for card.id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.creator_id
     *
     * @return the value of card.creator_id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.creator_id
     *
     * @param creatorId the value for card.creator_id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.gmt_create
     *
     * @return the value of card.gmt_create
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.gmt_create
     *
     * @param gmtCreate the value for card.gmt_create
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.gmt_modified
     *
     * @return the value of card.gmt_modified
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.gmt_modified
     *
     * @param gmtModified the value for card.gmt_modified
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.is_public
     *
     * @return the value of card.is_public
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public Boolean getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.is_public
     *
     * @param isPublic the value for card.is_public
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.title
     *
     * @return the value of card.title
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.title
     *
     * @param title the value for card.title
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.card_description
     *
     * @return the value of card.card_description
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public String getCardDescription() {
        return cardDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.card_description
     *
     * @param cardDescription the value for card.card_description
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setCardDescription(String cardDescription) {
        this.cardDescription = cardDescription == null ? null : cardDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.img_src
     *
     * @return the value of card.img_src
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public String getImgSrc() {
        return imgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.img_src
     *
     * @param imgSrc the value for card.img_src
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc == null ? null : imgSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.label_name
     *
     * @return the value of card.label_name
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.label_name
     *
     * @param labelName the value for card.label_name
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.user_id
     *
     * @return the value of card.user_id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.user_id
     *
     * @param userId the value for card.user_id
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.card_text
     *
     * @return the value of card.card_text
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public String getCardText() {
        return cardText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.card_text
     *
     * @param cardText the value for card.card_text
     *
     * @mbg.generated Fri Jun 26 22:11:45 CST 2020
     */
    public void setCardText(String cardText) {
        this.cardText = cardText == null ? null : cardText.trim();
    }
}