package com.km.knowledgemessage.Model;

public class KnowledgeBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.card_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.review_time
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long reviewTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.gmt_create
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.gmt_modified
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.review_num
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long reviewNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.user_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.card_name
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private String cardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.creator_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.card_description
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private String cardDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.last_review_time
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private Long lastReviewTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge_base.label_name
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    private String labelName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.id
     *
     * @return the value of knowledge_base.id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.id
     *
     * @param id the value for knowledge_base.id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.card_id
     *
     * @return the value of knowledge_base.card_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.card_id
     *
     * @param cardId the value for knowledge_base.card_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.review_time
     *
     * @return the value of knowledge_base.review_time
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.review_time
     *
     * @param reviewTime the value for knowledge_base.review_time
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setReviewTime(Long reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.gmt_create
     *
     * @return the value of knowledge_base.gmt_create
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.gmt_create
     *
     * @param gmtCreate the value for knowledge_base.gmt_create
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.gmt_modified
     *
     * @return the value of knowledge_base.gmt_modified
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.gmt_modified
     *
     * @param gmtModified the value for knowledge_base.gmt_modified
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.review_num
     *
     * @return the value of knowledge_base.review_num
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getReviewNum() {
        return reviewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.review_num
     *
     * @param reviewNum the value for knowledge_base.review_num
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setReviewNum(Long reviewNum) {
        this.reviewNum = reviewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.user_id
     *
     * @return the value of knowledge_base.user_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.user_id
     *
     * @param userId the value for knowledge_base.user_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.card_name
     *
     * @return the value of knowledge_base.card_name
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.card_name
     *
     * @param cardName the value for knowledge_base.card_name
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.creator_id
     *
     * @return the value of knowledge_base.creator_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.creator_id
     *
     * @param creatorId the value for knowledge_base.creator_id
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.card_description
     *
     * @return the value of knowledge_base.card_description
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public String getCardDescription() {
        return cardDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.card_description
     *
     * @param cardDescription the value for knowledge_base.card_description
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setCardDescription(String cardDescription) {
        this.cardDescription = cardDescription == null ? null : cardDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.last_review_time
     *
     * @return the value of knowledge_base.last_review_time
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public Long getLastReviewTime() {
        return lastReviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.last_review_time
     *
     * @param lastReviewTime the value for knowledge_base.last_review_time
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setLastReviewTime(Long lastReviewTime) {
        this.lastReviewTime = lastReviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge_base.label_name
     *
     * @return the value of knowledge_base.label_name
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge_base.label_name
     *
     * @param labelName the value for knowledge_base.label_name
     *
     * @mbg.generated Sat Jul 04 22:11:30 CST 2020
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }
}