package com.km.knowledgemessage.Model;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.creator_id
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.card_url
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    private String cardUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.is_read
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    private Integer isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    private String notice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.creator_id
     *
     * @return the value of notice.creator_id
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.creator_id
     *
     * @param creatorId the value for notice.creator_id
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.card_url
     *
     * @return the value of notice.card_url
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public String getCardUrl() {
        return cardUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.card_url
     *
     * @param cardUrl the value for notice.card_url
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public void setCardUrl(String cardUrl) {
        this.cardUrl = cardUrl == null ? null : cardUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.is_read
     *
     * @return the value of notice.is_read
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.is_read
     *
     * @param isRead the value for notice.is_read
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice
     *
     * @return the value of notice.notice
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice
     *
     * @param notice the value for notice.notice
     *
     * @mbg.generated Thu Jun 25 08:27:26 CST 2020
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }
}