package com.km.knowledgemessage.Model;

public class UserLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.card_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    private Long cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.user_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_like.id
     *
     * @return the value of user_like.id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_like.id
     *
     * @param id the value for user_like.id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_like.card_id
     *
     * @return the value of user_like.card_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_like.card_id
     *
     * @param cardId the value for user_like.card_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_like.user_id
     *
     * @return the value of user_like.user_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_like.user_id
     *
     * @param userId the value for user_like.user_id
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}