package com.km.knowledgemessage.Mapper;

import com.km.knowledgemessage.Model.PublicCard;
import com.km.knowledgemessage.Model.PublicCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    long countByExample(PublicCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    int deleteByExample(PublicCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    int deleteByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    int insert(PublicCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    int insertSelective(PublicCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    List<PublicCard> selectByExampleWithRowbounds(PublicCardExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    List<PublicCard> selectByExample(PublicCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    PublicCard selectByPrimaryKey(Long cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") PublicCard record, @Param("example") PublicCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    int updateByExample(@Param("record") PublicCard record, @Param("example") PublicCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    int updateByPrimaryKeySelective(PublicCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_card
     *
     * @mbg.generated Tue Jun 30 09:12:39 CST 2020
     */
    int updateByPrimaryKey(PublicCard record);
}